### PR TITLE
Gsoc2021 quad float

### LINKED ISSUE #80: quad_float full precision eval_sqrt
All of `cpp_quad_float`s arithmetic operators work well for `4 * digits` bits of precision (though there are rare exceptions which need more attention). However, the current `eval_sqrt()` procedure, maybe because of it's reliance of `cpp_double_float`, **loses two extra bits of precision**.

The relatively straightforward solution to this is to avoid dependence on `cpp_double_float` (as done in David Bailey's QD):

```
eval_sqrt(result, x) {
      result = (1.0F / std::sqrt(std::get<0>(x.crep())));

      quad_float_type h = x * 0.5F;

      result += ((quad_float_type(0.5F) - h * result * result) * result);
      result += ((quad_float_type(0.5F) - h * result * result) * result);
      result += ((quad_float_type(0.5F) - h * result * result) * result);

      result *= x;
}
```

I have personally tried this and it does seem to provide full `4 * digits` bits of precision. However, it might be slower, and can benefit from optimization (e.g. use the self-correcting nature of Newton's iterations).

Should we look into the optimizations after GSoC and make use of the extra precision it provides right now?
Thoughts?

CC: @ckormanyos @cosurgi

### PR DESCRIPTION
**Pull request by sinandredemption**
Full precision `eval_sqrt` as discussed in #80

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi @sinandredemption it's always curiously failing on one single compiler in one individual test situation on GCC with `std=gnu++14` or `std=gnu++17`. I am not sure if this is a tolerance issue or related to the extremely limited range of `float`'s exponent.

Things you can try include:
- Excluding those tests for `float` and covering up the problem for us to deal with later (OK by me for the moment).
- Maybe adjust the exponent range in a [line like this](https://github.com/BoostGSoC21/multiprecision/blob/a4df1c1bee38eb23083242fb85e6be292796bca8/test/test_cpp_quad_float_arithmetic.cpp#L159) --- maybe try 0.1F instead of 0.2F.
- This might ultimately be related to the similar root cause of #35. I can investigate.

One other problem I am encountering with `cpp_quad_float<float>` is that read from string and all kinds of other operations almost fail at the outset due to the extremely limited range of `float`'s values of `min_exponent10`/`max_exponent10`, typically limited to 38 or so. The type has 30 decimal digits of precision and has almost overflowed/underflowed upon creation itself.

I would almost exclude (via `static_assert`) the existence of `cpp_quad_float<float>` for float having less than, say plus/minus 100 decimal range in its exponent.

Cc: @cosurgi

**Comment by sinandredemption** [comment]
> One other problem I am encountering with cpp_quad_float<float> is that read from string and all kinds of other operations almost fail at the outset due to the extremely limited range of float's values of min_exponent10/max_exponent10

This is the problem with `float_string_cvt.hpp` that we have discussed before. The solution is to this is relatively straightforward (just replace the two eval_muls by powers of ten with a single one). Note that the `max_exponent` of `cpp_quad_float<float>` is not capped. So it seems to me correct to say that the problem also lies with the `float_string_cvt.cpp` code.

**Comment by sinandredemption** [comment]
Also, in the [above commit](https://github.com/BoostGSoC21/multiprecision/pull/82/commits/5f22b882908459ca8b152adf96aaa49603c4bcea), I updated the test exponents to reflect the asymmetry of `[max_exponent, min_exponent]`.

**Comment by sinandredemption** [comment]
@ckormanyos Would you please look into why, of the all the tests, is `test_exp.cpp` failing (even though it was passing in the first few commits on this PR)?

**Comment by ckormanyos** [comment]
> @ckormanyos Would you please look into why, of the all the tests, is `test_exp.cpp` failing

I must admit, Fahad, there is an extremely unusual effect goinng on --- something I have not yet experienced.

@sinandredemption for some reason CI on your branch is attempting to run the `_qf` version of `test_exp.cpp`. However, I had only activated that in my branches. You did not pick that up from develop either. I studied this quite a bit, but could not solve the problem.

As a last resort, i have manually merged some of the needed stuff to get exponent tests working on quad into your branch in the hopes that you can move forward from there. I might have rattled the cage on some of your tolerances. if this goes green or fails, we must really look into those.

Let's see how CI cycles through...

**Comment by ckormanyos** [comment]
> Let's see how CI cycles through...

@sinandredemption so far so good. You must maybe replace a thing or two such as the following. I fiddled around with your new asymmetric handling of expenents in our homegrown add/sub/mul/div/sqrt tests. If (or when) this push cycles green, you need to re-try that.

I actually believe we ran into a Git glitch here, or we caused one via unanticipated automatic merge activities. But I was not able to reproduce the cause of these. So I did manual repairs.

**Comment by cosurgi** [comment]
> The type has 30 decimal digits of precision and has almost overflowed/underflowed upon creation itself.

this is an interesting case. In that paper (which I sent last week) they were dicussing the possibility of creating a multi_float type with as many limbs as necessary to cover the entire exponent range. It looks like `quad_float<float>` is the first such scenario. For now I would simply relax the tests as much an necessary in order to not drop this type completely. Later it might be interesting to investigate the multi_float types having maximum number of limbs which cover whole exponent range.
And of course write in documentation that `cpp_quad_float<float>` is experimental and should not be used in production.
Or maybe disable it:

> I would almost exclude (via static_assert) the existence of `cpp_quad_float<float>` for float having less than, say plus/minus 100 decimal range in its exponent.

This solution is also acceptable.

**Comment by ckormanyos** [comment]
Force push via removing branch protection

**Comment by cosurgi** [comment]
See also: https://github.com/BoostGSoC21/multiprecision/issues/83#issuecomment-898895282

**Pull request merged**
