### PR TITLE
Test decomposition / recomposition : string ↔ decimal ↔ binary ↔ binary

### PR DESCRIPTION
**Pull request by cosurgi**
This PR is mostly for trying [`test_cpp_double_float_decomposition.cpp`](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float_janek/test/test_cpp_double_float_decomposition.cpp) in the pipeline. I still could not nail down the exact problem. I suspect there are several bugs combined here. In total there are 56 test failures 

I think that at least one bug found by above code should have a relatively easy fix: the comparison `operator==` of two double_float numbers (hence "binary ↔ binary" in the PR title), when they are using different representations, such as: `n = a - b = c + d`. Where for number `n>0` all numbers `a`,`b`,`c`,`d` are positive (I mean: there is minus in `- b`, the lower limb in one representation is negative). That is: `(a - b) - (c + d) == 0`. They are the same number, but represented in a different way. Plenty of examples for this are shown in the console. Commenting out [this line](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float_janek/test/test_cpp_double_float_decomposition.cpp#L166) reduces the number of errors from 56 to 42, and there is still the test if numbers are the same : by [comparing their difference with zero](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float_janek/test/test_cpp_double_float_decomposition.cpp#L162).

Other errors most likely have to do with #26 and maybe #35 or #20.

But #50 with #26 together are another story: some of the errors happen, because this decomposition / recomposition does not care about `numeric_limits` and often encounters nonzero bits (The `norm != 0` check) after "exhausting" the amount of bits provided by `numeric_limits`. This is a tricky error: when you look at [this loop](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float_janek/test/test_cpp_double_float_decomposition.cpp#L67), it is sort of clean, in a way that `numeric_limits` would require extra treatment which would raise questions "why such convoluted code?".

So basically these tests expose some deficiencies in the code. And yet, at the moment I have no clear idea how to fix them.

And also, some part of the code is commented out, because it produces an **[infinite loop!](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float_janek/test/test_cpp_double_float_decomposition.cpp#L200)** Not even a crash. I suspect some mishandling of infinities somewhere in the code.

BTW, I tried to run [`test_cpp_double_float_comparision.cpp`](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float_janek/test/test_cpp_double_float_comparision.cpp) and [`test_cpp_double_float_constructors.cpp`](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float_janek/test/test_cpp_double_float_constructors.cpp) but they fail to compile. @ckormanyos : Is that expected behavior at the current state, or did I misconfigure something on my end?

Also [`test_cpp_double_float_io.cpp`](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float_janek/test/test_cpp_double_float_io.cpp) compiles but produces errors (probably related with errors produced by the tests introduced in this PR).

CC @sinandredemption so you can glance at this, but no need to pause your work on quad float, I'm looking forward to it! :)

### CODE REVIEW

**Comment by cosurgi** [comment]
Also I'm not sure how to add the test to CI now, this  e795079 apparently does not produce expected errors, but some other errors :)

**Comment by cosurgi** [comment]
> test_cpp_double_float_comparision.cpp and test_cpp_double_float_constructors.cpp but they fail to compile.

Ah, ok. You are working on it: https://github.com/BoostGSoC21/multiprecision/issues/12#issuecomment-888514467 :)

**Comment by ckormanyos** [comment]
Hi @cosurgi thanks for investigating these issues.

> not sure how to add the test to CI now

At the moment, I have reduced the tests to mostly those already present/used in the existing Boost.Multiprecision, with slight adaption to running with `cpp_double_float<T>`.

The CI tests run in two test suites in the so-called _jam_ file. The actual selection of OS-es, compilers and which test suite runs is done in the YAML file.

It is actually easy to add/remove tests from the _jam_ file for instance in the test suite called _dq_qf_tests_ [here](https://github.com/BoostGSoC21/multiprecision/blob/8347e449dd58d94249de94ba2ed3d9a489483c7d/test/Jamfile.v2#L113).

**Comment by ckormanyos** [comment]
In the past week or so, most of my efforts have been on the administrative aspects of this repo, with the exception of a bit of tech on `eval_log()` and `eval_exp()`. This administrative work has been intended to move the `cpp_double_float<T>` class toward formal test/correctness/behavior as a Boost.Multiprecision backend.

That way, if/when we solve the remaining technical problems, we will have a nice class ready to go. After that, the quad-float case should be _much_ easier to bring down this pathway.

**Comment by cosurgi** [comment]
Note: part of discussion happened here: https://github.com/BoostGSoC21/multiprecision/commit/766899bb2b05e8f47832d58b99d166913fb496d1#commitcomment-54340141

**Comment by sinandredemption** [comment]
Hello @cosurgi 

I'm on my smartphone right now, but on a first look I noticed that the condition in `extra_normalize()` should be, _in theory_, already met via `normalize()`

In David Bailey's QD paper he mentions that the conditions for which the given normalisation worked are unknown (aka not mathematically proven). Could this be related to what we are seeing now?

EDIT: Link to the paper: https://web.mit.edu/tabbott/Public/quaddouble-debian/qd-2.3.4-old/docs/qd.pdf (see page 6 for the comment "Necessary conditions for this renormalization algorithm to work correctly are, unfortunately,
not known...")

**Comment by cosurgi** [comment]
@sinandredemption :
> […] `extra_normalize` […] In David Bailey's QD paper he mentions that the conditions for which the given normalisation worked are unknown (aka not mathematically proven). Could this be related to what we are seeing now?

Yes, this is quite possible. So I am wondering: maybe only this one special case isn't covered?
The special case being: the non-zero first bit is farther away than the number of bits.


@ckormanyos :
> > yes. Exactly. I see three different solutions
> > 3. advertise in documentation that the meaning of digits is a little sloppy in this type.

> This solution has previously successfully been used in Boost.Multiprecision. We handle extra digits within the general description of the so-called _guard_ _digits_ of a floating-point type. Some existing backends, for instance, do actually have more digits internally than those published in the `digits` member of `std::numeric_limits`. The data type, `cpp_dec_float` in particular has rather many (and varying) counts of guard digits.

I adapted the decomposition loop to be more forgiving in the aspect of amount of `digits`. The tests now pass. But they pass only after `extra_normalize` is called. Let us hope that it is only this particular case where it causes problems.

**Comment by ckormanyos** [comment]
These commits are fascinating. In the commit text, I see the phrase "CI should pass". Yes. CI does pass.

What tolerances are being used on the arithmetic tests in these passing CI run(s)?

**Comment by cosurgi** [comment]
> What tolerances are being used on the arithmetic tests in these passing CI run(s)?

Short answer is tricky. But I will try:

1. the decomposition loop [accepts existence](https://github.com/BoostGSoC21/multiprecision/pull/57/files#diff-8ce98636352ad37d2f0d1f88c11d031b89c5ca520570fa2db2f5ff520587ddeaR72) of guard bits (they were not needed for float, double, long double, float128, cpp_bin_float, MPFR)
2. string → decimal ↔ binary allows 1 ULP error

Longer answer:

So, Fahad found the main problem: it was a missing call to `normalize(…)` function. I expanded a bit on this trail and added  `extra_normalize(…)` function. We are on the right track to squash this bug. Currently the problem is that:

1. `normalize(…)` is called in [incorrect](https://github.com/BoostGSoC21/multiprecision/pull/57/files#diff-8ce98636352ad37d2f0d1f88c11d031b89c5ca520570fa2db2f5ff520587ddeaR173) [places](https://github.com/BoostGSoC21/multiprecision/pull/57/files#diff-8ce98636352ad37d2f0d1f88c11d031b89c5ca520570fa2db2f5ff520587ddeaR223) we should find a right spot for these calls inside cpp_double_float routines. Basically: we discovered that they are missing. But we don't know yet where they are missing.
2. I have added an [extra test](https://github.com/BoostGSoC21/multiprecision/pull/57/files#diff-8ce98636352ad37d2f0d1f88c11d031b89c5ca520570fa2db2f5ff520587ddeaR243) which compares between number constructed from decimal string and number constructed from binary representation. And here - for the sake of passing the pipeline - I allowed 1 ULP error. It would be great if we could get this error down to 0 ULP. This test could be just three lines long if `boost::math::float_distance` was compiling with cpp_double_float. So right now it is quite long. But while writing it, I discovered that Fahad is right in his concerns (*) about `normalize(…)` not being proved mathematically. I observed even 0.125 ULP error, which is technically impossible in any floating point number.
3. And the cause of all of these problems, we are pretty confident now, is located in the fact that sometimes even `extra_normalize(…)` produces a number which has nonzero bits further away than `digits` away possible. They are nonzero in place where they should not exist. I made the decomposition loop [much more forgiving](https://github.com/BoostGSoC21/multiprecision/pull/57/files#diff-8ce98636352ad37d2f0d1f88c11d031b89c5ca520570fa2db2f5ff520587ddeaR72), being able to accept some extra guard bits. This wasn't necessary before in this loop neither for `cpp_bin_float` nor MPFR nor `float128` type nor any other type I tested this loop with. `cpp_double_flaot` is the first which needs special treatment.

(*) I refer to the comment above: https://github.com/BoostGSoC21/multiprecision/pull/57#issuecomment-891958996 "Necessary conditions for this renormalization algorithm to work correctly are, unfortunately, not known..."

Conclusion 1: we should put calls to `normalize(…)` in few more places in cpp_double_float.cpp

Conclusion 2: if we get later more problems with these "dangling" bits, it may be quite useful for debugging tricky cases (even in [quad_float](https://github.com/BoostGSoC21/multiprecision/pull/57/files#diff-8ce98636352ad37d2f0d1f88c11d031b89c5ca520570fa2db2f5ff520587ddeaR386) I presume) to fully implement the `extra_normalize(…)` function to exactly zero these extra bits which are further away than `digits` allows them to exist. Currently it zeroes only the simplest case: when the [entire number is smaller](https://github.com/BoostGSoC21/multiprecision/pull/57/files#diff-bb9459c4a1f6866e23101b1428b9f6a910b63310156b202b3946d414fcb92071R305) than `digits` allows.

Conclusion 3: it is possible that handling implicit bits #26 will remove some of these problems. But I doubt it will remove all "dangling" bits. They will simply happen less often. The limitation being: these limbs cannot start with a zero bit. Their exponent is always shifted to the place of the first nonzero bit. Which - at the end of the representation creates the dangling bits.

**Comment by cosurgi** [comment]
> These commits are fascinating. In the commit text, I see the phrase "CI should pass". Yes. CI does pass.

Thank you :)

**Comment by cosurgi** [comment]
OK. Now a mystery before us. Will CI pass all the checks implemented so far?

My main concern is that somewhere in the code we assumed that `digits` are what they were before: `2 * <digits of underlying type> - 2`. And used `-1` or `-2` somewhere based on that. Then some of the math calculations could break. So I am not sure what will happen. But if this passes, we would have a quite elegant solution.

**Comment by cosurgi** [comment]
Notwithstanding that now string → decimal ↔ binary check now allows 2 ULP error.

And `epsilon()` needs an update.

And `normalize(…)` calls need to be put somewhere.

And for debugging a fully implemented `extra_normalize(…)` might be useful.

**Comment by ckormanyos** [comment]
Final tests are cycling with a few comments added to the arithmetic tests and a nightly build in the CI plan. I will merge this to develop as soon as the tests cycle.

**Comment by ckormanyos** [comment]
Hi @cosurgi and @sinandredemption many, many thanks for this work and your associated dilligent, untiring efforst refining the algorithms and numerical correctness of `cpp_double_float`. Thanks also @jzmaddock for your advice along the way.

**Pull request merged**
