### PR TITLE
Gsoc2021 quad float

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by sinandredemption** [comment]
@ckormanyos While you wait for the checks, I wanted to ask you this: what would be the best way for `eval_*` procedures to use specialized versions for native types? Here is what I am currently thinking:

```
void eval_add(cpp_quad_float, cpp_quad_float) { ... }
void eval_add(cpp_quad_float, nativefloat) { ... }

template <typename floattype, typename numerictype, std::enable_if<digits(numerictype) <= digits(floattype)>>
void eval_add(cpp_quad_float<floattype>, numeric_type) { eval_add(cpp_quad_float, nativefloat(numerictype)) }
```

Apologies for the horrible pseudo-code, hope it got my thoughts across.

**Comment by ckormanyos** [comment]
>  way for `eval_*` procedures to use specialized versions for native types

Hi @sinandredemption you are on the right path on that.

Basically, you provide specialized versions which are enabled/disabled via clever, appropriate `enable_if` template paramters.

From another project called `e_float`, I can share these kinds of lines below. It is another project altogeter, but you get the point. In this case, I had a special optimization for multiplication with built-in signed integral type.

```
  inline void eval_multiply(e_float& result, const e_float& x, const e_float& y)
  {
    result.representation() = x.crepresentation() * y.crepresentation();
  }

  template<typename SignedIntegralType,
           typename std::enable_if<(   (std::is_integral<SignedIntegralType>::value == true)
                                    && (std::is_signed  <SignedIntegralType>::value == true))>::type const* = nullptr>
  void eval_multiply(e_float& result, const SignedIntegralType& n)
  {
    result.representation().mul_signed_long_long(static_cast<std::int64_t>(n));
  }
```

**Comment by ckormanyos** [comment]
> provide specialized versions which are enabled/disabled

One more detail @sinandredemption in your specialized versions, you will need to decide if the integral/floating-point built-in type has a value that is larger/smaller-equal than the float-constituent of double/quad-float. This decision can be either via software in the routine itself (if enable-if on `long` `long`) or at compile-time via template parameters. This is sadly going to be a bit tricky, but we can deal with it i believe...

**Comment by sinandredemption** [comment]
Thank you for your valuable advice, @ckormanyos 

Please check [this PR](https://github.com/BoostGSoC21/multiprecision/pull/99) where I have tried an implementation of all of things we discussed.

**Comment by ckormanyos** [comment]
> check this PR where I have tried an implementation of all of things we discussed

It is great @sinandredemption. Thanks Fahad, I can really see the performance improvement on those unary and binary arithmetic operations with built-in types.

I would leave it at that state for now. There is, however, one further potential set of optimizations that can be considered in this area. You can `enable_if` on a given operation for _all_ built in types. Then within the subroutine itself logic can determine at run-time if the value does or does not exceed the maximum value of the integral part of the constituent part. Based on this run-time decision, either the optimized, less-complex routine can be called or (if the value exceeds the limit), the full construction and operation can be carried out. Since most integral values at run-time actually do fit into the constituent part, this can be an improvement on long integral types, other float types, etc.

But as i said, you already crunched out a really good improvement on this PR mentioned above. You can table this idea and we could pull it out at a later stage and see if it actually does any good or not, which it may or may not...

**Pull request merged**
