### PR TITLE
Double fp backend alternate algos

### PR DESCRIPTION
**Pull request by sinandredemption**
This PR is a proposal for alternate implementation of algorithms for add/sub/mul/div based on Chistopher's (@ckormanyos) [adaption](https://github.com/BoostGSoC21/multiprecision/blob/develop/example/q_float/q_float/q_float.h) of Keith Briggs/Victor Shoup's [work](https://github.com/libntl/ntl/blob/main/src/quad_float.cpp).

### CODE REVIEW

**Comment by sinandredemption** [comment]
Hello @ckormanyos @cosurgi 

Almost every time I run performance tests from [performance_test_df.cpp](https://github.com/BoostGSoC21/multiprecision/blob/develop/performance/performance_test_df.cpp), the new algorithms come out around 20-50% faster. I wonder if this can be replicated on other machines as well.

Aside from performance, are there any other considerations we must take into account before adapting the new algorithms?

**Comment by ckormanyos** [comment]
> I run performance tests from [performance_test_df.cpp](https://github.com/BoostGSoC21/multiprecision/blob/develop/performance/performance_test_df.cpp), the new algorithms come out around 20-50% faster. I wonder if this can be replicated on other machines as well.

Yes. I have also made this experience. It seems like Briggs got it right all those years ago.

> Aside from performance, are there any other considerations we must take into account before adapting the new algorithms?

When CI runs green (as it has done), many tests on the `cpp_double_fp<T>` template run. I have tried the alternate algorithms on `specfun` locally and there are some strange behaviors that I have not yet localized regarding `NaN`.

To be honest, I have not fully investigated these.

At the moment, the existing tests do not use `specfun` as we are running lots of arithmetic tests on this new backend using functions-and-limits and arithmetic tests.

So based on this exact PR, both styles of algorithms are equivalent.

Hmmm... The `double-double` concept is not an exact science. So I do not know which style of algorithms is better or more reliable. Personally I've used the Briggs algorithms since last century and never had a problem.

I do not at the moment know exactly how to make an unbiased decision, but I'm tending toward the faster algorithms, assuming we can straighten out NaNs and specfun as we move forward.

**Comment by ckormanyos** [comment]
This seems like a big step, but I would be OK if you merged these algos to our Fork's develop branch.

As a second step, I'd like to try them out on the full drone/Circel-CI/GHA testing on our real multiprecision branch in the parent repo. But we can do this potential second step later.

If you like to merge this PR, I'd say go ahead.

Cc: @sinandredemption and @cosurgi

**Comment by ckormanyos** [comment]
It seems like getting `cpp_double_fp` to be Boost-ready for 1.82 is not realistic so 1.83 is the earliest time slot. Thus we have time to figure out and/or even switch back and forth multiple times between algos.

So in summary, if you would like to push these algos as the new _front_ _runner_ for `cpp_double_fp` then that is fine and good for me as well.

**Comment by sinandredemption** [comment]
Alright, I will go ahead with the merge. I request you (@ckormanyos) to check one thing before though: there are many changed files, a lot of which this PR does not target. Can you please check that the changed files aren't actually breaking or rolling back anything?

**Comment by ckormanyos** [comment]
Hi Fahad (@sinandredemption) I did a big review, synchronized with develop branch of the parent repo and also eliminated som (now) unused code.

I also re-activated the Drone and CircleCI runs (for the first time ever) on our fork, witho9ut any knowledge if these will or will not run based on Fork's permissions.

Specfun is expected to be a bit problematic, but do-able, down the road.

Let's see how algos, functions and limits run through GHA on this PR...

**Comment by ckormanyos** [comment]
Hi Fahad (@sinandredemption) great job on this.

Cool. CI on in this CI on our Fork has run green and many arithmetic, and function-and-limit tests have passed.

Please feel free to merge any time of your convenience.

Whatever hrúrdles come up, we can try to handle them with these algos. If we ultimately decide to switch back, that is possible as well. Let's go with these algos and see if we can get some more progress on `specfun´, which i will look into more closely shortly.

**Pull request merged**
