### PR TITLE
Function tests maybe were disabled at times

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi Fahad (@sinandredemption) there is a mysterious, recurring failure in some bug-case testing in `test_pow_df.cpp` around line(s) 795.

We should see if this bug is present for both sets of algorithms. It is something with inf and/or NaN. This _might_  be what is bothering us on `specfun`. If you like, take a look.

I'll first get a chance to resolve this issue in a day or so...

If/when we go green here, I'd like to query why we still have troubles running `specfun`.

Cc: @cosurgi

**Comment by ckormanyos** [comment]
Hi @sinandredemption

>  a mysterious, recurring failure in some bug-case testing

At first glance, this is a non-caught overflow in multiplication routine that subsequently gets improperly converted to NaN.

I believe that the multiplication routine needs to do a better job _catching_  overflow and properly setting the result to `inf`. I can look into this soon. Or if you  get a chance to fix, please feel free to go for it.

**Comment by sinandredemption** [comment]
@ckormanyos I'm looking right into it. If I find something, I'll let you know!

**Comment by sinandredemption** [comment]
@ckormanyos The old Bailey style multiplication works well with test_pow_df.cpp, while also preserving one more bit of precision at all times. I'll mention more of my thoughts on this in #136.

**Comment by ckormanyos** [comment]
> old Bailey style multiplication works well with test_pow_df.cpp, while also preserving one more bit of precision 

Oh nice catch! Two wins for the price of one! Nice.

I'm not totally sure, but I think we need to think a little more about voluntarily _catching_ overflow in multiplication. One maybe silly first-pass idea would be to do a cursory check of the result of multiplying (`hi_left * hi_right`) and seeing if this is infinite. I have a `constexpr` check for `isinf()` in the `detail` section, so that won't mess up the `constexpr`-ness of multiplication. I do not, however, know how to check for overfloy on multiply in the best way.

**Comment by ckormanyos** [comment]
Hi Fahad (@sinandredemption) the failing tests include definitely trigonometric functions `sin()` and/or `cos()` for `cpp_double_fp_backend<float>`.

The range of that type is so limited that there might be tolerance problems. or the story could reveal a bit more behind the scenes.

I can probably handle these. i'll take a look tomorrow and see what's up on these if you haven't solved the problem by then. I think these should (at least I hope) be relatively straightforward.

**Comment by ckormanyos** [comment]
OK. It's a run-time assertion going haywire. It crawled in potentially within your recent changes. i can catch this error on a variety of compiler locally. I'm kind of finished for today, but this should be straightforward enough to find and fix.

I'll take a look when I get a chance...

**Comment by ckormanyos** [comment]
> a run-time assertion going haywire. It crawled in potentially within your recent changes. 

Hi Fahad (@sinandredemption) the run-time assertion failures originate from very large arguments to `sin()`/`cos()` for `cpp_double_fp< 4-byte-float >`. As a trivial first-step, I simply disabled these particular instantiations in the `sin()`/`cos()` tests.

This might need a closer inspection later down the road. But let's find out if anything else in addition is going on.

**Comment by sinandredemption** [comment]
> the run-time assertion failures originate from very large arguments to sin()/cos() for cpp_double_fp< 4-byte-float >

Thinking out loud here: we have open issue #136 concerning unacceptable precision loss with cpp_double_fp< 4-byte-float > that we haven't addressed yet.

**Comment by ckormanyos** [comment]
>> the run-time assertion failures originate from very large arguments to sin()/cos() for `cpp_double_fp< 4-byte-float >`

> we have open issue https://github.com/BoostGSoC21/multiprecision/issues/136 concerning unacceptable precision loss with `cpp_double_fp< 4-byte-float >` that we haven't addressed yet

Indeed. That's a good point. I fear, however, we might have an additional issue here.

These `sin()`/`cos()` tests all pass when using your/our original add/sub/mul/div algorithms from the GSoC timeframe itself.

The first test case that fails on `sin()` for `cpp_double_fp< 4-byte-float >` occurs when `k = 1` in the loop [here](https://github.com/BoostGSoC21/multiprecision/blob/a8474a44539250a9f478f4a6645aadf491ca87b2/test/test_sin.cpp#L197).

The next step might be to do a case study on exactly that trigonometric calculation with _original_-_Bailey_-versus-_Briggs_-_style_ algos and see if there is a difference. And if so, which kind. Do any of these algos get the right answer in the first place or is there a deeper issue with rounding or NaN hangning around?

**Comment by cosurgi** [comment]
> failures originate from very large arguments to `sin(`) / `cos()`

I once had trigonometric function failures for very large arguments, and the problem was a small error when calculating modulo two Pi in order to reduce the argument to be within range of two Pi.

**Comment by ckormanyos** [comment]
> had trigonometric function failures for very large arguments, and the problem was a small error when calculating modulo two Pi in order to reduce the argument to be within range of two Pi

Indeed Janek (@cosurgi) good point.

Well we found an error in the regular Multiprecision tests for `sin()` / `cos()` that did, in fact, lead to very large arguments for trigonometric functions. This was solved and the problems are no longer, let's say, visible.

I do, however, believe that there might be an issue hiding somewhere here still. I will generate some neutral test code and investigate.

Cc: @sinandredemption

**Comment by ckormanyos** [comment]
Nice job Fahad (@sinandredemption)

Regarding the small detail mentioned above, I'll prepare a test case and description that is relevant to it.

This is green for the moment, so merging.

**Comment by ckormanyos** [comment]
See also #137

**Pull request merged**
