### PR TITLE
Final refinements for GSoC wrap-up for cpp_quad_float

### PR DESCRIPTION
**Pull request by sinandredemption**

### CODE REVIEW

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

You might be delighted to see that the constructor from long long has been sped-up considerably.

Also, I request you to include the refined constructor tests in the CI, after due consideration and feedback.

**Comment by sinandredemption** [comment]
Also, please do check the the constructor from four floats [here](https://github.com/BoostGSoC21/multiprecision/blob/9cd9e82e677a9ad5903d46218d595824f2ae8eaf/include/boost/multiprecision/cpp_quad_float.hpp#L250). I am not sure if this is the cleanest possible implementation, but I think a constructor from four floats is convenient at times. Please feel free to provide suggestions, I can remove/modify this or use workarounds if you suggest.

**Comment by ckormanyos** [comment]
>  a constructor from four floats is convenient at times.

This is a tough design choice. A numerical type is not a tuple, not an array and not any internal representation. From that perspective, its constructors should be nothing but those suitable for conversion from built-ins. On the other hand, convenience constructors that closely retain compatibility with the underlying internal representation are quite useful. if possible, I usually make such convenience constructors private and access them via friendship to the class.

**Comment by ckormanyos** [comment]
> delighted to see that the constructor from long long has been sped-up considerably

@sinandredemption hi Fahad. Nice! Oh yeah, I am definitley happy to see that. I just ran some tests and it looks like a great improvement. Division is the only real trouble spot remaining.

**Comment by ckormanyos** [comment]
> request you to include the refined constructor tests in the CI

Hi @sinandredemption may you remind me of the exact name of the file? And do you also want tests with `float128`?

**Comment by sinandredemption** [comment]
> Hi @sinandredemption may you remind me of the exact name of the file? And do you also want tests with float128?

The file name is [`test_cpp_quad_float_constructors.cpp`](https://github.com/BoostGSoC21/multiprecision/blob/fee15e9537a7e4335df170fe74d5d67fbb8429c7/test/test_cpp_quad_float_constructors.cpp). Yes, let's see if any new errors come up with float128.

**Comment by sinandredemption** [comment]
> I usually make such convenience constructors private and access them via friendship to the class.

In the current implementation, the constructor from four floats is implemented only in `cpp_quad_fp_backend`. I am still unsure of whether it should be included in our final code or not.

**Comment by ckormanyos** [comment]
> see if any new errors come up with `float128`

Needed a little patching. Tests are cycling in my branch... Let's see.

**Comment by ckormanyos** [comment]
> Tests are cycling in my branch... Let's see.

Oh, of course. The constructor tests are failing for `cpp_quad_fp_backend<double>(long double)` on GCC having 10-byte `long` `double`. The range of 10-byte `long` `double` significantly exceeds that of 8-byte `double`on these platforms.

I am not sure if this is an artifact of the test code or if it is actually in the constructor(s).

@sinandredemption could you please, Fahad, take a look? You can find the test failures in my most recent CI run, which is not yet a PR until we solve this problem...

**Comment by sinandredemption** [comment]
@ckormanyos The problem is a rather silly one: during attempts to convert from `long double` to `double` the exponent overflows. Let me try out a patch ASAP

**Pull request merged**
