### PR TITLE
Gsoc2021 double float chris modify and test

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi @sinandredemption this PR merges your recent developments and adds a couple of little changes that have been made to get CI _going_ _green_.

Please feel free to update your branch from develop of the fork any time. I have tried to incorporate your changes into develop via merging your active branch into mine, then merge mine to develop of the fork.

**Comment by ckormanyos** [comment]
There are still isolated, spurious test failures for extreme values of exponent. I think we _might_ need to look into some tolerance(s) at some point later.

**Comment by sinandredemption** [comment]
> There are still isolated, spurious test failures for extreme values of exponent.

@ckormanyos what specific tests are you referring to that are failing?

**Comment by ckormanyos** [comment]
> what specific tests are you referring to that are failing

Hi @sinandredemption I failed to make a snapshot of the failed test and simple re-ran the CI job.

I will attempt to reproduce this claim of failed test case(s) and when (or if) I have an actual failing test case (or if one can be found), i will post it.

**Comment by ckormanyos** [comment]
> attempt to reproduce this claim of failed test case(s) 

There is at least one failure in, I believe, multiplication of `double_float<float>` [here](https://github.com/BoostGSoC21/multiprecision/runs/3101680372?check_suite_focus=true#step:4:40). It seems like it might be in multiplication.

There is another failure [here](https://github.com/BoostGSoC21/multiprecision/runs/3101680687?check_suite_focus=true#step:4:36) that I am having difficulty interpreting.

**Comment by sinandredemption** [comment]
Thank you, @ckormanyos. I will try to reproduce and fix these issues and report back.

**Pull request merged**
