### PR TITLE
Add some tests for long double and float128

### PR DESCRIPTION
**Pull request by cosurgi**
I am a bit tired today, so I will push what I have done so far with this. The `long double` appears to work, while `float128` mostly has some problems with the constructors.

### CODE REVIEW

**Comment by cosurgi** [comment]
It looks like one of the errors is because ADL is forced to be ignored with this line in the headers: `{return ::fabs((double)__lcpp_x);}`

**Comment by sinandredemption** [comment]
Hello @cosurgi 

Thank you for experimenting with `long double` and `float128`. I will merge these changes as soon as I review your contributions more carefully.

> The long double appears to work, while float128 mostly has some problems with the constructors.

Would you mind elaborating which specific test seems to fail? My guess is that `int64` and other integral types shouldn't be problematic, so maybe the issue is in constructors from other `cpp_double_float<>` types.

EDIT: My bad. It appears that the constructor for float128 is missing.

Cheers,
Fahad

**Comment by cosurgi** [comment]
Hi @sinandredemption thank you for looking into `float128`. I think I have fixed the C++11 problem in this branch. If the CI passes maybe better to merge this branch, because it already has `long double` tests working. While `float128` works only in single file: `test_cpp_double_float_arithmetic.cpp`

@ckormanyos what would you say?

**Comment by cosurgi** [comment]
We have [this error](https://github.com/BoostGSoC21/multiprecision/pull/23/checks?check_run_id=3104038578):

```
[FAILED] while performing '2.358593801908192302096166914359e-16' * '2.149198216548286427671835427656e+295'
```

but not reproducible. More recent [test showed](https://github.com/BoostGSoC21/multiprecision/pull/23/checks?check_run_id=3104252706):

```
[FloatingPointType = float]: Assertion `fabs(a) >= fabs(b) || a == 0.0 || !isnormal(a)' failed.
```

**Comment by ckormanyos** [comment]
> what would you say?

Hi @cosurgi

I say move confidently and strongly on develop branch of the fork.

There are, however, two items.
1. Could you please merge my new `asan` tests in CI from my branch into yours prior to your merge to develop of the fork?
2. Both errors that you mention above have crept into all CI runs off and on. We do not need to solve them yet... This means if you re-run CI, you are likely (after one or more re-runs) to go green eventually, as these errors are sporadic. There are, however, definitely these two things going on. Something with accuracy in one or more arithmetic operation(s) and another run-time assert that when failing (stranglely enough) seems to fail on clang (or this might be just a coincidence).

@sinandredemption is looking into these two type(s) of errors and there is growing awareness in our team regarding these.

But if you can go green, please disregard those little inconsistencies and plow steadily on... into develop of the fork.

**Comment by cosurgi** [comment]
> 1. Could you please merge my new asan tests

ok. I did here `git rebase gsoc2021_double_float_chris_modify_and_test` to add your commits f3c299e4, 14a2bd97, 4e58b1fc.

BTW, I am mostly used to gitlab where `git rebase` is the standard practice, because the git log is then more linear and easier to read. I mean: no more problems with some commits being lost. But I suspect that `git merge` instead of `rebase` is the standard practice on github?

> 2. Both errors that you mention above have crept into all CI runs off and on.

OK, in that case, let's merge this to both branches, the `develop` and `gsoc2021_double_float` so that nothing is lost and @sinandredemption can open a new MR on whichever of these two branches.

**Pull request merged**
