### PR TITLE
Gsoc2021 double float chris

### PR DESCRIPTION
**Pull request by ckormanyos**
Very preliminary preview of `cpp_quad_float` arithmetic tests

### CODE REVIEW

**Comment by ckormanyos** [comment]
Hi @cosurgi and @sinandredemption I upped the tests to 1/4 million per operator and get sporadic fails on subtraction.

I wonder if I changed/deleted something important? Anyone see anything?

**Comment by sinandredemption** [comment]
> 
> 
> Hi @cosurgi and @sinandredemption I upped the tests to 1/4 million per perator and get sporadic fails on subtraction.
> 
> I wonder if I changed/deleted something important? Anyone see anything?

Hello @ckormanyos. Excuse me for not being clear enough. The subtraction surprisingly fails at the default accuracy level as mentioned [here](https://github.com/BoostGSoC21/multiprecision/issues/62#issuecomment-893365963) and [here](https://github.com/BoostGSoC21/multiprecision/commit/b8052d2c0c7e7d5cdda2138f4f1fa6698bdf8052#commitcomment-54453814). I am looking into the problem.

**Comment by sinandredemption** [comment]
@ckormanyos Nevermind, seems like the problems is with `cpp_double_float<>`

Can I suggest we also report the `hexfloat` representation that cause the failing cases? Or would that be against the Boost convention?

**Comment by ckormanyos** [comment]
> The subtraction surprisingly fails at the default accuracy level as mentioned ...

> I am looking into the problem

Thanks @sinandredemption. The above comments from my side pertain to `cpp_double_float`. For the moment, I simply provided one single more bit tolerance to add/sub tests. This is a workaround.

If you do find out anything about operators `+`  and `-` in either of the backends, please don't hesitate to add repairs...

This PR also provides a very first glimpse of some arithemtic tests running on the `cpp_quad_float` backend wrapped for Multiprecision. Lots of work to go on that. But some tests are already actually passing. I'll comment more on this in #51. I will, however, move further/future qf efforts to their respective branch(es).

**Comment by ckormanyos** [comment]
OK. I added one more bit of tolerance to add/sub on `cpp_double_float` arithmetic tests. I can't see any functional difference in folder-to-folder comparisons from what I already pushed this morning. So I'll go ahead and push this PR to develop.

After that, I'll leave `cpp_double_float` for a short while and concentrate on the Boost-ification of `cpp_quad-float`, as tracked in #51.

**Pull request merged**
