### PR TITLE
Gsoc2021 double float

### PR DESCRIPTION
**Pull request by sinandredemption**
@ckormanyos If everything goes green, you might want to include `test_cpp_double_float_constructors.cpp` in the CI tests

### CODE REVIEW

**Comment by sinandredemption** [comment]
@ckormanyos I cancelled the workflow after ~20mins of tests with no result. Should I have waited instead?

**Comment by ckormanyos** [comment]
> cancelled the workflow after ~20mins of tests with no result. Should I have waited instead?

Hi @sinandredemption it depends on the situation. For open source, GHA grants us 20 server processes parallel at one given time. Our CI on a PR has a lot more than 20 server jobs. So if you have a few commits on PRs running back-to-back, it can get to be quite a lengthy traffic jam.

If you want to terminate a sequence of running build(s), it can make sense to terminate the eraliest builds first andthen observe your latest builds.

**Comment by ckormanyos** [comment]
In general @sinandredemption we have actually let `cpp_double_fp_backend` fall a bit behind. We might need special, sequential, little steps of synchronization to bring this up to the level  of `cpp_quad_fp_backend`. So if this PR turns out to be too tedious or difficult, we can retry later or reduce the scope of changes, if that helps.

**Comment by ckormanyos** [comment]
Hi @sinandredemption I took the liberty of re-starting one of the CI actions. it almost seemed like GHA might have had a bit of a glitch.

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

I have cancelled the tests you started. The problem seems to be in my changes which might cause , so I will try to issue a fix ASAP

**Comment by ckormanyos** [comment]
> problem seems to be in my changes which might cause , so I will try to issue a fix ASAP

Copy that. I do, however, recommend cuation regarding time constraints. If these changes lead to numerous revisions or time-consuming runs, please feel free at any time to revert to a state such as yesterday's. We have good stuff for this project and can always refine later.

So give it a good try, then see how it goes, with backup to be revert any time being OK.

**Comment by sinandredemption** [comment]
@ckormanyos The arithmetic tests were failing. Turns out this was due to an obvious yet tricky bug in the operator+= and operator-=. Have a look at the changes in the recent commit in case you're curious.

Let us see if all the tests pass now.

EDIT: Seems like the tests are passing :)

**Comment by ckormanyos** [comment]
>  tests are passing 

Great job @sinandredemption. Please merge when you are ready.

**Comment by sinandredemption** [comment]
@ckormanyos I would also request you to confirm the numbers I posted in #107 once I merge, since there is a chance that those numbers are too good to be true.

**Comment by ckormanyos** [comment]
> confirm the numbers I posted in #107 once I merge,

Done. Confirmed good on double-float. See #107 

@sinandredemption

**Pull request merged**
