### PR TITLE
Typos specfun Jam maybe now run and fail

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by ckormanyos** [comment]
OK this is a good failing state, if that makes any sense.

- We have regular tests running (arithmetic, functions and limits)
- We use hybrid Original-GSoC/Briggs algos
- specfun_cpp_double_double is running but failing (as expected).

So as soon as we work out specfun, we are really getting close. I do expect, however, that it will take quite some effort to get all of specfun running on `cpp_double_double`

Cc: @sinandredemption

**Comment by ckormanyos** [comment]
So there have now been improvements to:

- Reading string values (a helper from `cpp_dec_float` has been used).
- Catching infinity, division-by-zero and NaN better during division.
- We also wrote some more class assignement operators.

All _regular_ tests pass.

The state of `specfun` tests continues to gradually improve.

In `specfun` tests, there are now 11 failing files. The forms of failure are in at least two different classes.

The test failures in `specfun` include:

- Simple tolerance errors (such as in the final test file `powm1_sqrtp1m1`as shown in [the log here](https://github.com/BoostGSoC21/multiprecision/actions/runs/4000344311/jobs/6865361310)).
- Gross errors involving non-finite result / control-value.

The first class (tolerances) are simple enough. Either we have to bump up some tolerances for some `specfun` tests specifically and individually for the `cpp_double_double` tests. Or alternatively some specializations and improvements of `eval_`-whatever functions _could_ help in certain cases, logarithms with argument near 1 being such a potential case.

The gross errors are of a bit more concern, as these might be related to non-caught add/sub/mul/div, etc. with infinities and/or NaNs, or string conversion from values near the min/max. There could be also problems in the add/sub/mul/div routines themselves, as I'm still not sure if Briggs-type or Bailey-type algos are the right ones to use (or a combination thereof).

At any rate, we need to identify some exact test `specfun` test cases that fail and step them through (which is possible but challenging) to see what's up on these classes of errors. There are many failurs for large arguments in elliptic integrals, maybe too many to initially digest. Some other tests only have a few gross errors. These might be eiasier to understand in the first round.

Cc: @sinandredemption

**Comment by ckormanyos** [comment]
I was a bit silly and mistakenly fired up CI again. The two tests failing are `specfun` on the `cpp_double_double` type (which at the moment is the only double-fp backend being tested in `specfun`).

But these two tests are also not included in branch protection.

So Fahad (@sinandredemption) when CI runs through, and if you like, you can merge this PR. If you don't get a chance or if you'd prefer for me to do that, i merge this evening.

We keep getting closer...

**Comment by ckormanyos** [comment]
Thank you Fahad (@sinandredemption)

**Comment by sinandredemption** [comment]
It is my pleasure working with you, Chris (@ckormanyos). I'll get back to investigating specfun by tomorrow.

**Comment by ckormanyos** [comment]
> back to investigating specfun by tomorrow

You too Fahad (@sinandredemption) I also enjoy working with you. So we keep moving forward.

Basically now:

- See if fundamental algos add/sub/mul/div are correct and catch all infinities, NaNs, zeros, etc.
- Finish `specfun` tests.

I've learned a few things recently and i'll spend a few more words on them in offline chats and other issues. I still think we might be having some problems with the add/sub/mul/div algos insofar as thes may lead to infinities (or improperly catch them).

**Pull request merged**
